Github Actions - Export Kotlin Files (#5)
Will run ./gradlew generateProtos and generate Kotlin files from newly added protos.

The Kotlin files will be pushed to the ksharma-xyz/Kotlin-Proto repo.

diff --git a/.github/workflows/gen-kotlin.yaml b/.github/workflows/gen-kotlin.yaml
--- a/.github/workflows/gen-kotlin.yaml
+++ b/.github/workflows/gen-kotlin.yaml
@@ -1,31 +1,93 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Generate Kotlin
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "gen-kotlin"
-  gen-kotlin:
-    # The type of runner that the job will run on
+  generate-kotlin:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      - name: Checkout repo
+        uses: actions/checkout@v4
 
-      # Runs a single command using the runners shell
-      - name: Run generateProtos Task
+      - name: List directory structure before building
+        run: ls -R
+
+      - name: Generate Protos
         run: ./gradlew generateProtos
 
+      - name: List generated Kotlin files for debugging
+        run: |
+          find lib/build/generated/source/wire/ -type f -name "*.kt" || echo "Directory not found"
+
+      - name: List generated Kotlin files
+        id: list-kotlin-files
+        run: |
+          files=$(find lib/build/generated/source/wire/ -type f -name "*.kt")
+          echo "$files" > generated_files.txt
+          echo "KOTLIN_FILES=$(cat generated_files.txt)" >> $GITHUB_ENV
+
+      - name: List generated Kotlin files
+        run: |
+          gen_files=$(find lib/build/generated/source/wire/ -type f -name "*.kt")
+          if [ -z "$gen_files" ]; then
+            echo "Directory not found or no files found"
+          else
+            echo "gen_files_list<<$gen_files"
+          fi
+
+      - name: Upload generated Kotlin files
+        uses: actions/upload-artifact@v4
+        with:
+          name: generated-kotlin-files
+          path: lib/build/generated/source/wire/**/*.kt
+
+      - name: Checkout target repo
+        uses: actions/checkout@v4
+        with:
+          repository: 'ksharma-xyz/Kotlin-Proto'
+          token: ${{ secrets.TOKEN }}
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: generated-kotlin-files
+          path: ./generated
+
+      - name: Get Unix Timestamp
+        id: get-timestamp
+        run: echo "TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV
+
+      - name: Create Branch
+        run: |
+          timestamp=$(date +'%s')
+          branch_name="branch-${timestamp}"
+          git checkout -b $branch_name
+          git push origin $branch_name
+          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
+
+      - name: Create Pull Request
+        uses: peter-evans/create-pull-request@v6
+        with:
+          token: ${{ secrets.TOKEN }}
+          branch: ${{ env.BRANCH_NAME }}
+          committer: Github Actions Bot <41898282+github-actions[bot]@users.noreply.github.com>
+          author: Github Actions Bot <41898282+github-actions[bot]@users.noreply.github.com>
+          commit-message: "Add generated Kotlin files ${{ env.TIMESTAMP }}"
+          title: "Add generated Kotlin files ${{ env.TIMESTAMP }}"
+          body: |
+            ### Description
+            
+            Automated PR to add generated Kotlin files from [Proto-API](https://github.com/ksharma-xyz/Proto-API)
+            
+            ### List of files added:
+            ${{ env.KOTLIN_FILES }}
+            
+            ### Config
+            Configuration of the workflow is located in `.github/workflows/gen-kotlin.yaml`.
+          base: main
